spring.application.name=Clinicas

server.port=9003
#Configuracion de EUREKA
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:9000/eureka
spring.datasource.url=jdbc:postgresql://localhost:5432/microservicio-clinica
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true